# Generated by Django 5.0.6 on 2024-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_borrowedbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
