# Generated by Django 5.0.6 on 2024-07-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_borrowedbook_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
